// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simpleapp.proto

package simpleapp_service_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserRequest) Reset()         { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()    {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a7f02ffe317e7d, []int{0}
}

func (m *LoginUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserRequest.Unmarshal(m, b)
}
func (m *LoginUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserRequest.Marshal(b, m, deterministic)
}
func (m *LoginUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserRequest.Merge(m, src)
}
func (m *LoginUserRequest) XXX_Size() int {
	return xxx_messageInfo_LoginUserRequest.Size(m)
}
func (m *LoginUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserRequest proto.InternalMessageInfo

func (m *LoginUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserResponse) Reset()         { *m = LoginUserResponse{} }
func (m *LoginUserResponse) String() string { return proto.CompactTextString(m) }
func (*LoginUserResponse) ProtoMessage()    {}
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a7f02ffe317e7d, []int{1}
}

func (m *LoginUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserResponse.Unmarshal(m, b)
}
func (m *LoginUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserResponse.Marshal(b, m, deterministic)
}
func (m *LoginUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserResponse.Merge(m, src)
}
func (m *LoginUserResponse) XXX_Size() int {
	return xxx_messageInfo_LoginUserResponse.Size(m)
}
func (m *LoginUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserResponse proto.InternalMessageInfo

func (m *LoginUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RegisterUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a7f02ffe317e7d, []int{2}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a7f02ffe317e7d, []int{3}
}

func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(m, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetInfoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a7f02ffe317e7d, []int{4}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

func (m *GetInfoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetInfoResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a7f02ffe317e7d, []int{5}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginUserRequest)(nil), "simpleapp.service.v1.LoginUserRequest")
	proto.RegisterType((*LoginUserResponse)(nil), "simpleapp.service.v1.LoginUserResponse")
	proto.RegisterType((*RegisterUserRequest)(nil), "simpleapp.service.v1.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "simpleapp.service.v1.RegisterUserResponse")
	proto.RegisterType((*GetInfoRequest)(nil), "simpleapp.service.v1.getInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "simpleapp.service.v1.getInfoResponse")
}

func init() {
	proto.RegisterFile("simpleapp.proto", fileDescriptor_f1a7f02ffe317e7d)
}

var fileDescriptor_f1a7f02ffe317e7d = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0xd5, 0x0c, 0x94, 0x9c, 0x50, 0x0b, 0xa6, 0x43, 0x94, 0xa9, 0x84, 0xff, 0x20, 0x12,
	0xfe, 0x3c, 0x01, 0x6c, 0x20, 0x58, 0x82, 0x60, 0x40, 0x2c, 0x81, 0x1c, 0x96, 0x25, 0x62, 0x1f,
	0xbe, 0xb4, 0xc0, 0x1b, 0xf1, 0x98, 0x88, 0x36, 0x09, 0x2d, 0xb2, 0x14, 0x86, 0x8e, 0xe7, 0xfb,
	0xee, 0xfb, 0xee, 0x7e, 0x32, 0xf4, 0x59, 0x15, 0xf4, 0x8a, 0x19, 0x51, 0x4c, 0xd6, 0x94, 0x46,
	0x0c, 0x7e, 0x1f, 0x18, 0xed, 0x58, 0x3d, 0x63, 0x3c, 0x3e, 0x89, 0xae, 0x60, 0xf5, 0xda, 0x48,
	0xa5, 0xef, 0x18, 0x6d, 0x8a, 0x6f, 0x23, 0xe4, 0x52, 0x84, 0xb0, 0x3c, 0x62, 0xb4, 0x3a, 0x2b,
	0x30, 0xe8, 0x0c, 0x3b, 0x7b, 0x7e, 0xda, 0xd4, 0x3f, 0x3d, 0xca, 0x98, 0xdf, 0x8d, 0xcd, 0x03,
	0x6f, 0xda, 0xab, 0xeb, 0xe8, 0x08, 0xd6, 0x66, 0xbc, 0x98, 0x8c, 0x66, 0x14, 0x01, 0x74, 0x0b,
	0x64, 0xce, 0x64, 0xed, 0x55, 0x97, 0xd1, 0x0d, 0xac, 0xa7, 0x28, 0x15, 0x97, 0x68, 0x17, 0x91,
	0x7e, 0x0c, 0x83, 0x79, 0xbb, 0xd6, 0x05, 0x86, 0xd0, 0x93, 0x58, 0x5e, 0xea, 0x17, 0x53, 0x67,
	0xf7, 0xc0, 0x53, 0x79, 0x25, 0xf3, 0x54, 0x1e, 0x1d, 0x42, 0xbf, 0x51, 0xb4, 0xd9, 0x9d, 0x7e,
	0x79, 0xe0, 0xdf, 0x4e, 0x18, 0x9f, 0x13, 0x89, 0x47, 0xf0, 0x1b, 0x18, 0x62, 0x27, 0x76, 0xc1,
	0x8f, 0xff, 0x92, 0x0f, 0x77, 0x5b, 0x75, 0xd5, 0x16, 0x08, 0x2b, 0xb3, 0xc7, 0x8a, 0x7d, 0xf7,
	0xa0, 0x83, 0x6f, 0x78, 0xf0, 0x1f, 0x69, 0x15, 0x73, 0x0f, 0xdd, 0xea, 0x7e, 0xb1, 0xe5, 0x1e,
	0x9b, 0x07, 0x18, 0x6e, 0xb7, 0xa8, 0xa6, 0xbe, 0x17, 0x9b, 0x0f, 0x1b, 0x64, 0xcd, 0xc7, 0x67,
	0x22, 0x51, 0x27, 0xd2, 0x24, 0xae, 0xa1, 0xa7, 0xa5, 0xc9, 0xbf, 0x3d, 0xfb, 0x0e, 0x00, 0x00,
	0xff, 0xff, 0xda, 0x73, 0x77, 0x18, 0xca, 0x02, 0x00, 0x00,
}
